### ISSUE TITLE
設定 (とくにvim関係) について、OS毎にきちんと設計する

### ISSUE THREAD

**Issue by rudel-nao-akakura** [clxmochamalefic/dotfiles#1]
階層構造イメージ
- win
    - `init.ps1`
        - chocolatey などの初期投入パッケージの用意をするスクリプト
- mac
    - `init.sh`
        - homebrew などの初期投入パッケージの用意をするスクリプト
- linux
    - `init.apt.sh`
        - `apt` パッケージマネージャ用のスクリプト
    - `init.yum.sh`
        - `yum` パッケージマネージャ用のスクリプト
    - `init.sh`
        - 上記のどちらかをコールする初期投入パッケージの用意をするスクリプト
- vim
    - `init.vim`
        - nvim用設定ファイル
    - `ginit.vim`
        - nvim-qt用設定ファイル
    - `dein.toml`
        - dein用設定ファイル
    - `dein_lazy.toml`
        - dein用設定ファイル
    - windows
        - `init.vim.windows.first`
            - windows環境でのみ、そのままdein.vimをインストールできないので、一番ベーシックな `init.vim` を用意して実行させる必要があるので、それを用意
        - `init.vim.windows.ref`
            - windows環境でのみ、シンボリックリンクを貼ることができないので、 `~/repos/dotfiles/vim/init.vim` へのリファレンスファイルを用意
        - `ginit.vim.windows.ref`
            - windows環境でのみ、シンボリックリンクを貼ることができないので、 `~/repos/dotfiles/vim/ginit.vim` へのリファレンスファイルを用意
        - `init.ps1`
            - 上記3ファイルの実行等を自動化するposh用シェルスクリプト

**Comment by clxmochamalefic** [comment]
すでに目的は達成されているのでクローズ
お疲れさま、過去の私
